### ISSUE TITLE
Is this the same look as spark ais to raster?

### ISSUE THREAD

**Issue by elduddz** [UKHO/AzurePipelinesAgents#2]
https://github.com/UKHO/AzurePipelinesAgents/blob/e717f32f2d5f5533fa2bbb40422721aedc95fb60/azure-pipelines.yml#L25

@eganjs looks the same right? Yet asks me for AZURE_PASSWORD, which is defined in the variables!

**Comment by eganjs** [comment]
I'm told you need the Azure CLI, and need to do a login (`az login` ) before each Terraform usage, but I'm not in a position to test this myself.

**Comment by elduddz** [comment]
Nope, agreed not needed TF_VAR_ did it.
